name: Gerar Nova Chave

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar keystore
        run: |
          keytool -genkey -v -keystore devocionalplus-release-key-v2.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -alias devocionalplus \
            -storepass "Dv$(date +%s)Plus2026" \
            -keypass "Dv$(date +%s)Plus2026" \
            -dname "CN=DevocionalPlus, OU=App, O=DevocionalPlus, L=Brasil, S=BR, C=BR"
          echo "storepass=Dv$(date +%s)Plus2026" > senha.txt

      - name: Upload da chave
        uses: actions/upload-artifact@v4
        with:
          name: nova-chave
          path: |
            devocionalplus-release-key-v2.jks
            senha.txt
