name: Publicar Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: stable

      - run: flutter pub get
      - run: flutter build apk --release

      - name: Publicar no GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Última versão"
          make_latest: true
          files: build/app/outputs/flutter-apk/app-release.apk
